sudo: required
services: 
  - docker

before_install:
  - docker build -t shingiuwa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shingiuwa/docker-react npm run test -- --watchAll=false